"""Add total and rest fields to Receipt model

Revision ID: 04f5d7c4ffb1
Revises: 7c7b689f4b2b
Create Date: 2025-02-13 23:16:55.014097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f5d7c4ffb1'
down_revision: Union[str, None] = '7c7b689f4b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('receipts', sa.Column('rest', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'rest')
    op.drop_column('receipts', 'total')
    # ### end Alembic commands ###
